SELECT 'CREATE DATABASE project2'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'project2')\gexec

create table person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName varchar NOT NULL,
    birthDate DATE NOT NULL
    );

create table book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    author varchar NOT NULL,
    year int,
    personid int REFERENCES person(id) ON DELETE SET NULL
    );

insert into Person(fullName,birthDate) values('Didier Daniel Duhautbout', '1981-12-10');
insert into Person(fullName,birthDate) values('Aurelie Vasques Belque', '1948-08-24');
insert into Person(fullName,birthDate) values('James Willam Ross','1981-12-12');
insert into Person(fullName,birthDate) values('Pascal Antony Vendran', '1971-04-12');
insert into Person(fullName,birthDate) values('Rose Elena Jigoue', '1983-03-01');
insert into Person(fullName,birthDate) values('Пушкин Александр Сергеевич', '1981-12-10');

insert into book(title, author, year) values ('Lord of the Flies', 'William Gerald Golding', 1983);
insert into book(title, author, year) values ('«1984»', 'George Orwell', 1948);
insert into book(title, author, year) values ('Drei Kameraden', 'Erich Maria Remarque', 1936);
insert into book(title, author, year, personid) values ('Lord of the Flies', 'William Gerald Golding', 1983, 1);

