version: '3.4'

services:
    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dev
        ports: 
            - "5432:5432"
        restart: always
        volumes: 
            - database-data:$HOME/docker/volumes/postgres

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin:
